id: P4FB4F8DF
initial_creation_type: input
source_metadata:
  title: Katok Dampa Deshek Series
  language: bo
  description: 'Texts by Katok Dampa Deshek (kaḥ thog dam pa bde gshegs, 1122–1192),
    the founder of Katok Monastery:'
  volume:
    ea563e8e934f48c5984b5dd974c32b5d:
      title: The Last Testament of Katok Dampa Deshek
      parent: Last Testament
created_at: '2022-03-01T00:13:09.691281'
last_modified_at: '2022-03-01T00:13:09.691284'
statistics:
  total_words: 76
  total_non_words: 13
quality:
  non_words_ratio: 0.17
